### ISSUE TITLE
App not geting start 

### ISSUE THREAD

**Issue by Anilugale** [MapmyIndia/mapmyindia-maps-vectorSDK-android-sample-withREST-beta#1]
`/Volumes/Android/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed`

above log was printed at logcat 
following is the build.gradle file 
`apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.moreinfotech.test"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.cardview:cardview:1.0.0'
 //   implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.google.android.libraries.places:places:1.1.0'
    implementation project(path: ':mapSdk')
}`

**Comment by mdakram** [comment]
Hey @Anilugale what is mapSdk? and did you provide keys?

**Comment by Anilugale** [comment]
`configurations.maybeCreate("default")
artifacts.add("default", file('MapmyIndiaGLAndroidSDK_v6.7.4.aar'))`

mapSdk is project depandancy of MapmyIndiaGLAndroidSDK and verson v6.7.4

**Comment by Anilugale** [comment]
could you build lib in android 28 API level ?

**Comment by Anilugale** [comment]
working after the adding of mabox dependency
```
 implementation 'com.mapbox.mapboxsdk:mapbox-sdk-turf:3.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-gestures:0.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-geojson:3.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-core:3.1.0'
    implementation files('libs/MapmyIndiaGLAndroidSDK_v6.7.4.aar')
    implementation 'com.mapbox.mapboxsdk:mapbox-android-core:0.2.0' 
```
