### ISSUE TITLE
query

### ISSUE THREAD

**Issue by sanket099** [MapmyIndia/mapmyindia-maps-vectorSDK-android-sample-withREST-beta#2]
hey ...
i was wondering.. is there any way to add multiple markers (pointing to different locations) on the same map 

@MapmyIndia-Maps

**Comment by Saksham66** [comment]
@sanket099 Please find the below link for adding multiple markers 
https://github.com/MapmyIndia/mapmyindia-maps-vectorSDK-android-sample-withREST-beta/blob/master/app/src/main/java/com/mapmyindia/sdk/demo/java/activity/AddCustomInfoWindowActivity.java#L52
